-- =============================================================================
-- 001_sessions_schema.sql
--
-- New session-linked schema for the coffee grinder scale, replacing the
-- old flat `topup`/`progress`/`raw_data` tables (see D8/D9 in
-- .agent/DECISIONS.md, and .agent/design/topup-model.md §6 +
-- .agent/design/coast-effect.md §5 for the analysis that motivated this).
--
-- WHERE THIS LIVES AND WHY
-- -------------------------
-- Applied inside the existing `coffee_grinder` database, in a NEW schema
-- called `v2` — not `public` (where the old `topup`/`progress` tables live)
-- and not a new database. Reasoning:
--   * The old `raw_data` table lives in a *separate* database
--     (`coffee_grinder_raw`), specifically so it could grow independently.
--     But the whole point of this redesign is that raw samples, pulse
--     events, and sessions are now linked by a shared `session_id` FK —
--     Postgres cannot do cross-database foreign keys, so raw_samples has
--     to live in the same database as sessions/events. `coffee_grinder`
--     (not `coffee_grinder_raw`) was chosen as the shared home since that's
--     where the session-level and pulse-level data naturally belongs.
--   * A new schema (`v2`) inside the existing database — rather than
--     dumping new tables into `public` next to the old ones, or spinning
--     up a whole new database — keeps old and new cleanly namespaced
--     (`public.topup` vs `v2.sessions`) without the cross-database FK
--     problem, and lets PostgREST be pointed at exactly one schema
--     (`db-schema = "v2"`) so it never exposes the legacy tables at all.
--   * Old tables (`public.topup`, `public.progress`,
--     `coffee_grinder_raw.public.raw_data`) are UNTOUCHED by this
--     migration — no ALTER, no DROP. They keep being live historical data
--     other analysis depends on until D8's cutover is verified and
--     `coffee_grinder_api` is decommissioned.
--
-- ID STRATEGY
-- -----------
-- `sessions.session_id` is a UUID generated by the FIRMWARE (device-side),
-- not a Postgres-assigned serial. This matters structurally: the device
-- needs a session id to attach to every event/raw-sample row it posts
-- *during* the session, before the session's outcome is known — so the id
-- has to exist before the "this session succeeded" row is even written.
-- A client-generated UUID (v4, from the ESP32's hardware RNG) sidesteps
-- the chicken-and-egg problem a server-assigned serial would create.
-- `events.event_id` and `raw_samples.sample_id` ARE server-assigned
-- (GENERATED ALWAYS AS IDENTITY) — nothing needs to reference an event
-- before it's inserted, so there's no reason not to let Postgres assign
-- these and keep them compact.
--
-- WRITE LIFECYCLE (what the firmware/PostgREST interaction looks like)
-- ----------------------------------------------------------------------
--   1. POST v2.sessions   — one row, mode/requested/target weight known,
--      outcome='in_progress', at grind start.
--   2. POST v2.events      — one row per pulse (MAIN_GRIND first, then each
--      TOPUP pulse), fired with relay_on_at_ms/weight_before_g as soon as
--      known; PATCH the same row's weight_after_g/stable_at_ms once the
--      post-pulse reading settles.
--   3. POST v2.raw_samples — continuously, ~20Hz, throughout the session
--      (see "raw sample logging" note below).
--   4. PATCH v2.sessions   — once, at session end, setting final_weight_g,
--      outcome, completed_at (and the main-grind relay_off_at_ms/
--      stable_at_ms convenience copies, if not already set).
-- This is why the PostgREST role below needs UPDATE (not just INSERT) on
-- specific columns of `sessions` and `events` — an insert-only role literal
-- to the word could never record a session's actual outcome.
--
-- RAW SAMPLE LOGGING — kept, linked by session_id
-- --------------------------------------------------
-- coast-effect.md's entire analysis exists because relay-off/relay-on
-- timestamps and per-pulse settle times weren't persisted, forcing curve-
-- reconstruction from raw ADC samples after the fact. That curve data is
-- still valuable for exactly this kind of analysis (and for future model
-- work), so raw sampling is kept as its own table rather than dropped or
-- folded into `events` — it's fundamentally a different cardinality
-- (~20Hz continuous vs. one row per discrete pulse). `v2.raw_samples` adds
-- what the old `raw_data` table was missing: a `session_id` FK (eliminating
-- the wall-clock-proximity linkage heuristic coast-effect.md §1(b) had to
-- use) and a `grinder_state` tag per sample (eliminating the stable-segment
-- curve-walking reconstruction in the same section). Per AGENTS.md's data
-- infra decision (D8), ingestion moves from an opportunistic websocket
-- relay (today: only logged if a browser happened to have the live graph
-- open) to direct PostgREST posting, so capture becomes unconditional
-- rather than best-effort — this was flagged explicitly in coast-effect.md
-- §5 as something to not lose in the rewrite.
--
-- EVENT_TYPE vs. GRINDER_STATE — two related but distinct enums, on
-- purpose
-- --------------------------------------------------------------------
-- `events.event_type` (MAIN_GRIND / TOPUP) tags a *logical pulse* — one
-- row per relay-energize decision, matching topup-model.md §6's ask and
-- directly fixing the §0 data-quality bug in the old `topup` table (its
-- first row per session was silently the main grind's tail, not a real
-- topup pulse, because nothing tagged event type explicitly).
-- `raw_samples.grinder_state` (MAIN_GRIND / TOPUP_PULSE_ON / TOPUP_SETTLE
-- / STOPPING / FINALIZE) is a finer-grained *phase* tag per ADC sample,
-- matching coast-effect.md §5's ask exactly. It's finer than event_type
-- because a single TOPUP event's *lifetime* spans two raw-sample phases
-- (TOPUP_PULSE_ON while the relay is energized, TOPUP_SETTLE while
-- waiting for `isStable` afterward), and STOPPING/FINALIZE describe
-- final-session phases that aren't pulses at all. Collapsing both enums
-- into one would either lose the settle/stopping/finalize phases (if
-- restricted to event_type's 2 values) or force fake "event" rows for
-- non-pulse phases (if events.event_type absorbed all 5 values) — keeping
-- them on the two tables they naturally belong to avoids both problems.
--
-- SCOPE NOTE
-- ----------
-- This migration is additive-only: new schema, new tables, new roles.
-- It does not touch `public.topup`, `public.progress`,
-- `coffee_grinder_raw.public.raw_data`, or any existing role.
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS v2;
COMMENT ON SCHEMA v2 IS
  'Session-linked grinder dosing schema (D8/D9). Superseded/replaces the '
  'flat public.topup / public.progress / coffee_grinder_raw.public.raw_data '
  'tables for all NEW data going forward; those tables are left untouched '
  'as historical record. See .agent/design/db-schema/001_sessions_schema.sql '
  'for full design rationale.';

-- -----------------------------------------------------------------------------
-- v2.sessions — one row per grind session (main grind + its topup pulses).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS v2.sessions (
    -- Firmware-generated UUIDv4, assigned at grind start (before outcome is
    -- known — see "ID STRATEGY" above). Primary anchor every events/
    -- raw_samples row hangs off.
    session_id          UUID PRIMARY KEY,

    -- Server-side insert time (effectively "session start", since the
    -- device POSTs this row at grind start). Distinct from the ms-since-
    -- session-start offsets used everywhere else in this schema, which are
    -- all relative to this moment per the firmware's own `millis()` clock.
    started_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Set once, at session end (PATCH), when outcome/final_weight_g are
    -- known. NULL while a session is still in progress.
    completed_at          TIMESTAMPTZ,

    -- What kind of dose this was. 'api_custom' covers a target requested
    -- programmatically (e.g. future HTTP API/companion app) rather than
    -- chosen via the device's physical single/double buttons.
    mode                 TEXT NOT NULL
                          CHECK (mode IN ('single', 'double', 'api_custom')),

    -- What was actually asked for (button press or API caller), before any
    -- internal correction.
    requested_weight_g    REAL NOT NULL CHECK (requested_weight_g > 0),

    -- What the dosing logic actually aimed the main-grind stop condition
    -- at — requested_weight_g adjusted by the coast-offset / topup-margin
    -- correction (coast-effect.md §4's `target_grams_corrected` pattern).
    -- Equal to requested_weight_g when no correction is applied. Separating
    -- these two fields directly answers topup-model.md §6's ask to tell
    -- "the algorithm chose to undershoot on purpose" apart from "the
    -- algorithm missed".
    target_weight_g       REAL NOT NULL CHECK (target_weight_g > 0),

    -- Actual measured weight once the session finished (main grind + all
    -- topup pulses). NULL until the session completes.
    final_weight_g        REAL,

    -- 'in_progress' while the device is still dosing; set once at PATCH
    -- time. 'aborted' = user cancelled via button press mid-session;
    -- 'timed_out' = topup loop hit its max-attempts/timeout guard without
    -- reaching target_weight_g. Keeping these distinct from 'completed'
    -- stops abandoned sessions from silently polluting outcome statistics
    -- (topup-model.md §6's explicit ask).
    outcome               TEXT NOT NULL DEFAULT 'in_progress'
                          CHECK (outcome IN
                                 ('in_progress', 'completed', 'aborted', 'timed_out')),

    -- Main-grind relay timestamps, ms since started_at, per coast-effect.md
    -- §5 (`grinder_started_millis`/`grinder_stopped_millis`, already
    -- computed locally in main.cpp's grinderOn()/grinderOff() today but
    -- never persisted). Denormalized copies of the same fields also
    -- recorded on the MAIN_GRIND row in v2.events (pulse_index=0) — kept
    -- here too so a session's headline timing is readable without a join.
    relay_on_at_ms        INTEGER,
    relay_off_at_ms       INTEGER,
    -- When the post-main-grind coast/settle finished (isStable latched
    -- true and held) — turns coast_time/coast_weight into a direct lookup
    -- instead of coast-effect.md §1(b)'s curve-reconstruction heuristic.
    stable_at_ms          INTEGER,

    -- Free-text bean/burr/grind-setting tag, bumped manually by the owner
    -- on a bag or burr change. Lets future analysis attribute the ~12-15%
    -- rate drift topup-model.md §2.3 measured over 17 months to specific
    -- events instead of treating it as unexplained slow drift.
    grind_setting         TEXT,

    -- Firmware build identifier (e.g. git describe / semver). Enables
    -- clean before/after comparison of old vs. new topup algorithm
    -- directly from live data (topup-model.md §6).
    firmware_version       TEXT NOT NULL,

    -- Version tag of the persisted on-device dosing model struct (see
    -- topup-model.md §4.3's TopupModelV1) that was active for this
    -- session, if applicable. Nullable because not every session
    -- necessarily has a versioned model behind it (e.g. very first boot
    -- before any model persistence exists).
    model_version          TEXT
);

COMMENT ON TABLE v2.sessions IS
  'One row per grind session (main grind + its topup pulses). Written by '
  'the ESP32 directly to PostgREST: INSERT at grind start, PATCH at grind '
  'end. See topup-model.md §6 and coast-effect.md §5 for the analysis that '
  'motivated each column.';

CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON v2.sessions (started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_outcome ON v2.sessions (outcome);

-- -----------------------------------------------------------------------------
-- v2.events — one row per discrete pulse within a session (the main grind
-- itself, plus each topup pulse that follows it).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS v2.events (
    event_id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ON DELETE CASCADE is intentional here: a session is the natural unit
    -- of deletion for this device-authored data (e.g. cleaning up a test
    -- POST during PostgREST verification) — deleting a session should take
    -- its events and raw samples with it rather than requiring a manual
    -- multi-table cleanup. This is NOT used on the old public.topup/
    -- progress tables and never will be; those are untouched history.
    session_id             UUID NOT NULL
                          REFERENCES v2.sessions (session_id) ON DELETE CASCADE,

    -- MAIN_GRIND = the initial grind-to-target phase (always pulse_index
    -- 0, exactly one per session). TOPUP = a single relay pulse fired by
    -- the topup correction loop. See the "EVENT_TYPE vs. GRINDER_STATE"
    -- note at the top of this file for why TOPUP_SETTLE is NOT a value
    -- here (it lives on raw_samples.grinder_state instead).
    event_type            TEXT NOT NULL
                          CHECK (event_type IN ('MAIN_GRIND', 'TOPUP')),

    -- 0 for MAIN_GRIND; 1, 2, 3... in firing order for TOPUP pulses within
    -- the session. Lets analysis directly study "does pulse 2 behave
    -- differently from pulse 1" (topup-model.md §6) instead of the
    -- row-position heuristic topup-model.md §0 had to use on the old data.
    pulse_index            SMALLINT NOT NULL CHECK (pulse_index >= 0),

    -- Relay-energize/de-energize timestamps, ms since the session's
    -- started_at — the firmware-clock-measured values from
    -- grinderOn()/grinderOff() (coast-effect.md §1(b) point 1: these are
    -- precise millis() deltas, not estimates).
    relay_on_at_ms         INTEGER NOT NULL,
    relay_off_at_ms        INTEGER NOT NULL CHECK (relay_off_at_ms >= relay_on_at_ms),
    -- Denormalized for convenient querying (mirrors old topup.runtimemillis)
    -- without forcing every consumer to recompute it.
    runtime_ms             INTEGER GENERATED ALWAYS AS
                             (relay_off_at_ms - relay_on_at_ms) STORED,

    -- When isStable first latched true and held after this pulse's
    -- relay-off (coast-effect.md §5). NULL until the settle completes, or
    -- permanently NULL if the session was aborted mid-settle.
    stable_at_ms           INTEGER,

    -- Scale reading immediately before this pulse fired, and once settled
    -- afterward. weight_after_g is NULL until settle completes (filled in
    -- via the same PATCH that sets stable_at_ms).
    weight_before_g        REAL NOT NULL,
    weight_after_g         REAL,
    -- Denormalized (mirrors old topup.weightincrement) — automatically
    -- consistent with weight_before_g/weight_after_g since it's computed,
    -- not independently written.
    weight_increment_g     REAL GENERATED ALWAYS AS
                             (weight_after_g - weight_before_g) STORED,

    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE v2.events IS
  'One row per discrete relay pulse within a session: the main grind '
  '(pulse_index=0, event_type=MAIN_GRIND) plus each subsequent topup pulse '
  '(event_type=TOPUP). Written as INSERT (relay-on/weight-before known) '
  'then PATCH (relay-off/weight-after/stable_at_ms known once the pulse '
  'and its settle complete).';

CREATE INDEX IF NOT EXISTS idx_events_session_id ON v2.events (session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_session_pulse
  ON v2.events (session_id, pulse_index);

-- -----------------------------------------------------------------------------
-- v2.raw_samples — high-frequency (~20Hz) ADC/scale samples, linked by
-- session_id (and, where attributable, event_id).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS v2.raw_samples (
    sample_id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    session_id             UUID NOT NULL
                          REFERENCES v2.sessions (session_id) ON DELETE CASCADE,

    -- Which pulse this sample belongs to, when attributable (e.g. a sample
    -- taken during a specific TOPUP pulse's on-time or settle window).
    -- NULL is valid and expected for samples taken during phases that
    -- aren't part of any single pulse (e.g. STOPPING/FINALIZE tail
    -- samples after the last topup pulse's settle already completed).
    event_id               BIGINT
                          REFERENCES v2.events (event_id) ON DELETE SET NULL,

    -- ms since the session's started_at — same convention as the old
    -- raw_data.timestamp_ms (already relative to session_started_millis
    -- per coast-effect.md §1(b) point 2), kept unchanged so existing
    -- curve-analysis scripts port over with minimal changes.
    timestamp_ms            INTEGER NOT NULL,

    raw_value               BIGINT NOT NULL,
    filtered_value          REAL NOT NULL,
    -- The firmware's own isStable flag at this sample (same semantics as
    -- old raw_data.stable) — kept as-is; it's what loopStopping()/
    -- loopTopUp() actually gate on today, per coast-effect.md §3 point 3.
    stable                  BOOLEAN NOT NULL DEFAULT false,

    -- Fine-grained phase tag, one per sample. See "EVENT_TYPE vs.
    -- GRINDER_STATE" note at the top of this file. This is the field that
    -- eliminates coast-effect.md §1(b)'s stable-segment-walking
    -- reconstruction entirely — every sample already says what phase it's
    -- from.
    grinder_state            TEXT NOT NULL
                          CHECK (grinder_state IN
                                 ('MAIN_GRIND', 'TOPUP_PULSE_ON', 'TOPUP_SETTLE',
                                  'STOPPING', 'FINALIZE')),

    received_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE v2.raw_samples IS
  'High-frequency (~20Hz) raw scale samples, one row per ADC read, linked '
  'to the session (and, where known, the specific pulse) they belong to. '
  'Append-only from the device''s perspective — INSERT only, no PATCH. '
  'Kept unconditionally (not gated on a websocket client being connected, '
  'unlike the old raw_data table) once ingestion moves to direct PostgREST '
  'posting per D8.';

CREATE INDEX IF NOT EXISTS idx_raw_samples_session_id ON v2.raw_samples (session_id);
CREATE INDEX IF NOT EXISTS idx_raw_samples_session_ts
  ON v2.raw_samples (session_id, timestamp_ms);
CREATE INDEX IF NOT EXISTS idx_raw_samples_event_id ON v2.raw_samples (event_id);

COMMIT;

-- =============================================================================
-- Roles for PostgREST's own connection use.
--
-- Two-role split is PostgREST's standard pattern (see PostgREST docs,
-- "Authentication" / "db-anon-role"):
--   * `postgrest_authenticator` — the role PostgREST's own db-uri connects
--     as. LOGIN, but NOINHERIT and otherwise privilege-free: its only
--     capability is switching into postgrest_anon for the duration of a
--     request. This means even a leaked db-uri credential can't do
--     anything on its own beyond that role-switch.
--   * `postgrest_anon` — NOLOGIN, and the role that actually holds table
--     privileges. Every unauthenticated request (which, for this device-
--     only ingestion path, is every request — there's no JWT auth in this
--     v1 design; the firmware posts on the trusted home LAN) executes as
--     this role. This is where the real privilege scoping happens.
--
-- Deliberately NOT plain INSERT-only, even though the device only ever
-- needs to write: PostgREST needs SELECT on a table to return a
-- representation after INSERT (`Prefer: return=representation`, which the
-- firmware needs to learn e.g. the server-computed weight_increment_g), and
-- more fundamentally the finalize step (setting a session's outcome/
-- final_weight_g once known) is a PATCH — i.e. an UPDATE — not an INSERT.
-- An INSERT-only role would make it structurally impossible to ever record
-- how a session actually turned out. UPDATE is deliberately scoped to only
-- the specific columns that get patched after the fact (column-level GRANT),
-- not full-row UPDATE — the device can amend a session's outcome, but can't
-- rewrite its own recorded target_weight_g or requested_weight_g after the
-- fact.
--
-- Explicitly NOT granted anything on the old public.topup / public.progress
-- / coffee_grinder_raw.public.raw_data tables, and NOT granted anything
-- beyond schema v2 — this role has no visibility into legacy data at all.
--
-- Password for postgrest_authenticator is set separately, out-of-band (see
-- .agent/secrets/ — NOT committed, NOT inlined in this file). Run this
-- file with:
--   psql -v pw=<password> -f 001_sessions_schema.sql
-- i.e. pass the raw password value with NO surrounding quotes on the -v
-- flag — the :'pw' substitutions below already add SQL-literal quoting
-- themselves. Wrapping it in an extra pair of quotes on the command line
-- makes those literal quote characters part of the stored password
-- (a real mistake made and caught during this migration's first
-- application — see .agent/design/postgrest-deployment.md).
-- =============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgrest_anon') THEN
        CREATE ROLE postgrest_anon NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA v2 TO postgrest_anon;

GRANT SELECT, INSERT ON v2.sessions TO postgrest_anon;
GRANT UPDATE (final_weight_g, outcome, completed_at,
              relay_off_at_ms, stable_at_ms) ON v2.sessions TO postgrest_anon;

GRANT SELECT, INSERT ON v2.events TO postgrest_anon;
GRANT UPDATE (relay_off_at_ms, stable_at_ms, weight_after_g) ON v2.events TO postgrest_anon;

-- raw_samples is genuinely insert-only (and select, for return=representation):
-- no column is ever patched after the fact.
GRANT SELECT, INSERT ON v2.raw_samples TO postgrest_anon;

-- Note: role creation with a password can't be done inside a DO $$ ... $$
-- block, because psql's :'pw' variable substitution is plain text
-- substitution done before the query is sent, and it does not reach inside
-- a dollar-quoted string body. The \gexec idiom below (build the DDL as a
-- SELECT result, then execute it) is the standard psql workaround.
SELECT format('CREATE ROLE postgrest_authenticator LOGIN NOINHERIT PASSWORD %L', :'pw')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgrest_authenticator') \gexec

GRANT postgrest_anon TO postgrest_authenticator;
